version: "3.8"
services:
  prisma_db:
    container_name: "prisma_db_nest"
    image: "postgres:13"
    ports:
      - "5432:5432"
    volumes:
      - graphql_project:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  prisma_redis:
    image: redis:6.2-alpine
    container_name: "prisma_redis"
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  graphql_project:
  minio_data:
